disabled_rules: # rule identifiers to exclude from running
#  - colon
#  - comma
#  - control_statement
#  - cyclomatic_complexity
#  - file_length
#  - force_cast
#  - force_try
#  - function_body_length
#  - leading_whitespace
  - line_length
#  - nesting
#  - opening_brace
#  - operator_whitespace
#  - return_arrow_whitespace
#  - statement_position
#  - todo
#  - trailing_newline
#  - trailing_semicolon
#  - trailing_whitespace
#  - type_body_length
  - type_name
#  - variable_name_max_length
#  - variable_name_min_length
  - variable_name

excluded: # paths to ignore during linting. overridden by `included`.
  - Pods
  - ShinyGemHunterSlotsTests
file_length:
  - 150
  - 200
function_body_length:
  - 15
type_body_length:
  - 400 # Warning
  - 500 # Error
