app_icon './icon/Icon-1024.png'
app_rating_config_path './fastlane/metadata/itunes_rating_config.json'
automatic_release true
force true
overwrite_screenshots true
price_tier 0
skip_binary_upload true
submit_for_review false
submission_information({
  export_compliance_available_on_french_store: "false",
  export_compliance_contains_proprietary_cryptography: "false",
  export_compliance_contains_third_party_cryptography: "false",
  export_compliance_is_exempt: "false",
  export_compliance_uses_encryption: "false",
  export_compliance_app_type: nil,
  export_compliance_encryption_updated: "false",
  export_compliance_compliance_required: "false",
  export_compliance_platform: "ios",
  content_rights_contains_third_party_content: "false",
  content_rights_has_rights: "false",
  add_id_info_limits_tracking: "false",
  add_id_info_serves_ads: "false",
  add_id_info_tracks_action: "false",
  add_id_info_tracks_install: "false",
  add_id_info_uses_idfa: "false"
});
