fastlane_version "2.41.0"

default_platform :ios

platform :ios do
  before_all do
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Creating a code signing certificate and provisioning profile"
  lane :provision do
    produce(
      app_name: "ShinyGemHunterSlots",
      language: "English",
      app_version: "1.0",
      sku: "com.vantanllc.ShinyGemHunterSlots"
      )

    cert

    sigh(force: true)
  end

  desc "Create ipa"
  lane :build do
    current_build_number = latest_testflight_build_number(initial_build_number: 1)
    increment_build_number(build_number: current_build_number + 1)
    gym
  end

  desc "Upload to App Store"
  lane :upload_metadata do
    deliver()
  end

  desc "Deploy to Testflight"
  lane :beta do
    pilot(
      beta_app_description: "app description",
      beta_app_feedback_email: "vantan.llc@gmail.com",
      changelog: "app changelog",
      skip_submission: true,
      skip_waiting_for_build_processing: false,
      wait_processing_interval: 30
    )
  end

  desc "Calculate test code coverage score. Need to run test beforehand."
  lane :report_test_coverage do
    xcov(
      workspace: "ShinyGemHunterSlots.xcworkspace",
      scheme: "ShinyGemHunterSlots",
      output_directory: "xcov_output"
    )
  end
end

